[package]
name = "tttz-server"
version = "0.3.0"
authors = ["asrcpq <asrcpq@outlook.com>"]
edition = "2018"

[dependencies]
bimap = "*"
once_cell = "*"

[dependencies.tttz-mpboard]
path = "../mpboard"

[dependencies.tttz-ai]
path = "../ai"

[dependencies.tttz-protocol]
path = "../protocol"
