[package]
name = "mypuzzle-server"
version = "0.2.0"
authors = ["asrcpq <asrcpq@outlook.com>"]
edition = "2018"

[dependencies]
bincode = "*"
bimap = "*"
lazy_static = "*"

[dependencies.mypuzzle-mpboard]
path = "../mpboard"

[dependencies.mypuzzle-ai]
path = "../ai"
