[package]
name = "mypuzzle-server"
version = "0.1.0"
authors = ["asrcpq <asrcpq@outlook.com>"]
edition = "2018"

[dependencies]
lazy_static = "*"
termion = "*"
rand = "*"
bincode = "*"
bimap = "*"

[dependencies.mpboard]
path = "../mpboard"
