[package]
name = "mypuzzle-server"
version = "0.1.0"
authors = ["asrcpq <asrcpq@outlook.com>"]
edition = "2018"

[dependencies]
bincode = "*"
bimap = "*"
lazy_static = "*"

[dependencies.mpboard]
path = "../mpboard"
