[package]
name = "tttz-protocol"
version = "0.1.0"
authors = ["asrcpq <asrcpq@outlook.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
bincode = "*"

[dependencies.tttz-ruleset]
path = "../ruleset"
