[package]
name = "mypuzzle-ai"
version = "0.1.0"
authors = ["asrcpq <asrcpq@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "*"

[dependencies.mypuzzle-libclient]
path = "../libclient"

[dependencies.mypuzzle-mpboard]
path = "../mpboard"
