[package]
name = "tttz-ai"
version = "0.2.0"
authors = ["asrcpq <asrcpq@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "*"

[dependencies.tttz-libclient]
path = "../libclient"

[dependencies.tttz-mpboard]
path = "../mpboard"
