[package]
name = "tttz-mpboard"
version = "0.2.0"
authors = ["asrcpq <asrcpq@outlook.com>"]
edition = "2018"

[dependencies]
rand = "*"
lazy_static = "*"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.tttz-protocol]
path = "../protocol"
