[package]
name = "tttz-aibench"
version = "0.1.0"
authors = ["asrcpq <asrcpq@outlook.com>"]
edition = "2018"

[dependencies]
tttz-ai = {path = "../ai"}
tttz-libai = {path = "../libai"}
tttz-mpboard = {path = "../mpboard"}
