[package]
name = "tttz-libai"
version = "0.1.0"
authors = ["asrcpq <asrcpq@outlook.com>"]
edition = "2018"

[dependencies]
tttz-mpboard = {path = "../mpboard"}
tttz-protocol = {path = "../protocol"}
tttz-ruleset = {path = "../ruleset"}
