[package]
name = "mypuzzle-client"
version = "0.1.0"
authors = ["asrcpq <asrcpq@outlook.com>"]
edition = "2018"

[[bin]]
name = "mypuzzle-client"
path = "src/client.rs"

[[bin]]
name = "mypuzzle-ai1"
path = "src/ai1.rs"

[dependencies]
termion = "*"
bincode = "*"
rustyline = "*"

[dependencies.mpboard]
path = "../mpboard"
