[package]
name = "mypuzzle-client"
version = "0.1.0"
authors = ["asrcpq <asrcpq@outlook.com>"]
edition = "2018"

[[bin]]
name = "mypuzzle-client"
path = "src/client.rs"

[[bin]]
name = "mypuzzle-ai_vanilla"
path = "src/ai/vanilla.rs"

[dependencies]
termion = "*"
bincode = "*"

[dependencies.mpboard]
path = "../mpboard"
